### ISSUE TITLE
POSIX-shell functions are not supported

### ISSUE THREAD

**Issue by bam80** [dr-chip-vim-scripts/StlShowFunc#1]
ksh-style function definitions “function foo {}” are supported, but POSIX's "foo() {}” are not.
More on this here: [difference between “function foo() {}” and “foo() {}”](https://unix.stackexchange.com/questions/73750/difference-between-function-foo-and-foo)

The problem is addressed here:
[ [patch] POSIX shell functions support for Showing Current Function Name in Status Line (StlShowFunc) plugin ](https://groups.google.com/forum/#!topic/vim_dev/ZJVSrRShQb8)

I'll make PR later

@cecamp

**Comment by ivanalejandro0** [comment]
closing this before archiving repo, see https://github.com/dr-chip-vim-scripts/StlShowFunc/issues/5
