### ISSUE TITLE
can't switch StlShowFunc off from any buffer other than the first handled one

### ISSUE THREAD

**Issue by bam80** [dr-chip-vim-scripts/StlShowFunc#3]
To reproduce:
Issue `:StlShowFunc!` command in any secondary buffer of handled type.

The error:
```
No such variable: "b:stlshowfunc_keep"
```
@cecamp

**Comment by ivanalejandro0** [comment]
closing this before archiving repo, see https://github.com/dr-chip-vim-scripts/StlShowFunc/issues/5
