### ISSUE TITLE
Is this still being used?

### ISSUE THREAD

**Issue by ivanalejandro0** [dr-chip-vim-scripts/StlShowFunc#5]
Hey @bam80, is this repo still alive?

I'm thinking on archiving the dr-chip-vim-scripts org since I haven't used or touched the ZoomWin repo in many years.
I've never used the StlShowFunc repo so I'm asking you about it, but it looks like untouched for several years as well.

Thoughts?

**Comment by bam80** [comment]
Hi, yes I didn't use it too.
It still might have value for a history, but if you feel it's necessary to archive, I don't have more opposite arguments.

**Comment by ivanalejandro0** [comment]
yeah, I don't mean to delete it... just to set it as "archived", the purpose is to communicate that the repo is not getting any updates or activity, as well as not receiving issues any more.
Github also won't send notifications about potential issues with the org/repos to me.

I'll archive the org+repos then, feel free to contact me in the future if you'd like it to revert it or to own some of it.

Cheers!
